### ISSUE TITLE
After server restart conveyors are no long connected

### ISSUE THREAD

**Issue by Xander112** [Team-IO/taam#119]
just visualy
![2015-12-02_15 49 28](https://cloud.githubusercontent.com/assets/6298052/11533894/4c9e7ae0-990c-11e5-9650-bd6f03442639.png)

**Comment by Xander112** [comment]
in version 0.2

**Comment by Xander112** [comment]
they connect again when a item passes over them

**Comment by founderio** [comment]
That's a visual artifact when the are loaded. updateContainingBlockInfo() is only called once and the neighboring conveyors were not correctly loaded yet.
