### ISSUE TITLE
net.teamio.taam.content.BaseBlock.func_149689_a

### ISSUE THREAD

**Issue by Tsyklop** [Team-IO/taam#134]
I place Conveyor Sieve and game crash:
http://pastebin.com/M3m7sZRZ

And. Conveyor Sieve no have texture:
![2015-12-04_10 18 19](https://cloud.githubusercontent.com/assets/6783568/11584888/7cbe1644-9a70-11e5-8e05-0e9da8655a18.png)

**Comment by founderio** [comment]
The Sieve was actually completely missing.
Rather than doing a patchy workaround I just implemented it ;)
Will be in 0.4 / 1.0.

**Comment by Xander112** [comment]
0.4 will be released today the 4th of December 2015

Oliver Kahrmann <notifications@github.com> schrieb am Fr., 4. Dez. 2015
16:32:
