### ISSUE TITLE
[Suggestion(s)] Improvements

### ISSUE THREAD

**Issue by accessdenied0** [Team-IO/taam#144]
Hello Team-IO,

first I want to say I'm very impressed about this mod. It looks very cool, maybe a not fully "minecrafty" but I like the mechanics and ideas.

secondly allow me to suggest a couple of things, and if this is already planed or not useful I apologize:
- Conveyor belts recipe: I personal think the recipe is a bit expensive for just one of them. Maybe a increase or balancing would be awesome
- Other mod symbiosis:
  I like the parts you need to craft for a machine but these parts use very much raw materials (e.g. tank and copper wire) so it would be awesome if you can make them more unique
- Resin
  Resin is not in the OD (IC2 add some, too)

I hope this doesn't sound very rude,

access_denied

**Comment by Xander112** [comment]
Hi access_denied,

thanks for your suggestions we will try to fix as many of then as we can.
For the next time please consider creating separate issue (it is simple 
for us to manage and fix then)

xanderio
MCC (Modding Community Consultant) and Co-Founder of Taam Industries 
a.k.a. Team I/O

**Comment by founderio** [comment]
Folloow-Up issues have been created, this issue does not serve any purpose anymore.
