### ISSUE TITLE
Add the ability to disable and configure ore spawning

### ISSUE THREAD

**Issue by Rukachan** [Team-IO/taam#149]
Ores such as Copper and Tin have a config option to disable from spawning. Yet ores such as Bauxite, Kaolinite and Native Aluminium do not have such option.
Another feature would be to have the ability to configure the rate that the ores will spawn. Right now in my world Bauxite spawns way too often.

**Comment by Xander112** [comment]
actually all ore spawning Configs were completely ignored

**Comment by Xander112** [comment]
Also Bauxite is not a ore it is a typ of rock (like diorite or granite) . We only have a wrong texture and name for it.
