### ISSUE TITLE
Fix you bauxite spawn rate

### ISSUE THREAD

**Issue by EwyBoy** [Team-IO/taam#151]
Bauxite is spawning in WAY to big veins and WAY to often. You should really consider fixing this. I like this mod alot but all the bauxite is just ruining the world gen. Would be nice if you could fix it or at least add a config file for controlling the vein size and spawn rate per chunk. 
-Ewy

**Comment by Xander112** [comment]
Bauxite is not an Ore, it is a typ of Stone and in Dev it alredy has a 
driffernt texture.

**Comment by Xander112** [comment]
maybe by a littel and it will maybe spawn lower

**Comment by EwyBoy** [comment]
why not add a config for it?

**Comment by Xander112** [comment]
will be added in the next release
