### ISSUE TITLE
High tickrate then crash with ProjectE

### ISSUE THREAD

**Issue by luffykick** [Team-IO/taam#161]
Using the Red Morningstar from ProjectE right click mining ability, near Taam's Kaolinte ore causes the game to come to a complete stop, [Tickrate tanks]. Removing Taam has resolved the problem.

**Comment by luffykick** [comment]
forgot to mention I am on MC1.7.10 using ProjectE 1.9.4 & Taam 1.0.1

**Comment by Xanderio** [comment]
do you have any other mods installed

**Comment by luffykick** [comment]
Yes over 300+. Can you set your ProjectE.cfg config to "B:pickaxeAoeVeinMining=true" and see if you can reproduce? ill test an instance with just ProjectE and Taam in a sec and see if it still happens.

**Comment by Xanderio** [comment]
still can reproduce. I think this is a issue on Projekt E's site

**Comment by luffykick** [comment]
ok I just tested on a brand new instance with just ProjectE 1.9.4 & Taam 1.0.1. Here is what I got in the log.

>  [15:44:32] [Client thread/WARN]: Something's taking too long! 'root.tick' took aprox 131.388348 ms
[15:44:32] [Client thread/WARN]: Something's taking too long! 'root' took aprox 141.909407 ms
[15:44:32] [Client thread/WARN]: Something's taking too long! 'root.tick' took aprox 113.198022 ms
[15:44:32] [Client thread/WARN]: Something's taking too long! 'root' took aprox 119.713574 ms
[15:44:40] [Client thread/WARN]: Something's taking too long! 'root' took aprox 103.320157 ms

I was using the latest forge 1614. I downgraded to the recommended version... same thing.

To replicate this...
1. You need to be near the Taam ores
2. Have ProjectE.cfg config set to "B:pickaxeAoeVeinMining=true"
3. Power up the hammer by pressing V, then right click.

You should get a huge lag spike and all the entities will freeze around you, If you break any blocks nothing will drop. Kind of like when you lag on a server. the only way out for me is to forcefully close minecraft.

Ill let the ProjectE author know too, he might know how/if you can fix this.
