### ISSUE TITLE
[Suggestion] minecraft forum

### ISSUE THREAD

**Issue by Snipe13051** [Team-IO/taam#165]
Maybe it would help out to get more users to that mod if you also use http://www.minecraftforum.net/

Also the chance is higher to get more response for compatibility etc. would be nice to see your mod there because the information (updates etc.) is easier to follow in a real forum.

Thanks

**Comment by founderio** [comment]
@Xanderio Please check out.
At least a description page would be good, with references to team-io.net and curseforge..

**Comment by Snipe13051** [comment]
Also it's for us easier to discripe something because we can upload pictures over there and so it's easier to understand for you guys. :)

**Comment by Xanderio** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2634355-taam
