### ISSUE TITLE
Massive amounts of Copper ore generation

### ISSUE THREAD

**Issue by localzuk** [Team-IO/taam#214]
Every world I generate with 1.1.0-beta1 consists mostly of copper ore below the surface. I'm using the "Extreme 1.8.9 Mega Pack" from the Curse launcher. I have attempted to disable ore generation by editing the taam.cfg file as below:

`ldgen {
    # Should Taam generate Aluminum Ore in the World [default: true]
    B:generateAluminum=false

    # Should Taam generate B Ore in the World [default: true]
    B:generateBauxite=false

    # Should Taam generate Copper Ore in the World [default: true]
    B:generateCopper=false

    # Should Taam generate Kaolinte Ore in the World [default: true]
    B:generateKaolinite=true

    # Should Taam generate Tin Ore in the World [default: true]
    B:generateTin=false`

If you'd like any more info, or a copy of an example world, please ask and I'll gather whatever I can.

**Comment by Xanderio** [comment]
The ore genaration not being disable is is bug that is fix in the 
version of taam for minecraft 1.9

**Comment by localzuk** [comment]
Should it be generating every world nearly entirely made of copper?

**Comment by Xanderio** [comment]
no it should not. I'm right now trying to fix that

**Comment by founderio** [comment]
There was a typo somewhere in the code, always generating copper regardless of which ore was "checked", and another one loading the wrong settings per ore.
Fixed in the next release.
