### ISSUE TITLE
Duping problem

### ISSUE THREAD

**Issue by maestroke** [Team-IO/taam#244]
If you put the grinder on top of a hopper and drop stuff into the grinder, you will get both the initial item you dropped in and the products, they are probably both picking up the item instead of just 1 of them getting it

using: Taam-1.10.2-1.1.0-beta13.jar
Forge: forge-12.18.3.2185

**Comment by founderio** [comment]
Hmm.. interesting. Confirmed quite easily, I'll fix that ASAP.

**Comment by founderio** [comment]
Fixed in beta14: https://github.com/Team-IO/taam/releases/tag/1.10.2-1.1.0-beta14
