### ISSUE TITLE
Quick question, how does the fluid dryer work?

### ISSUE THREAD

**Issue by maestroke** [Team-IO/taam#250]
i wanted to use your method of generating obsidian, by pumping lava into the fluid dryer, but no matter what i do, the fluid dryer does nothing. how does it work?
if you want to see what my setup was, i also asked on /r/feedthebeast but to no avail, https://www.reddit.com/r/feedthebeast/comments/5kz5m7/cant_get_the_taam_fluid_dryer_to_work_to_make_me/

**Comment by Xanderio** [comment]
It looks like your pump is the wrong way around.

**Comment by maestroke** [comment]
It works, thank you very much
